application: literhub
version: 1
runtime: python
api_version: 1

handlers:

- url: /admin
  script: admin.py
  login: admin

- url: /admin/.*
  script: admin.py
  login: admin

- url: /.*
  script: home.py