application: literhub
version: 1
runtime: python
api_version: 1

handlers:
- url: /.*
  script: home.py
  
- url: /tasks/.*
  script: admin.py
  login: admin
 
- url: /.*
  script: not_found.py